## Supervised Learning Premier

<p>
The quality of data and the amount of useful information it contains is very key to the results of the machine learning algorithms.
Its important to examine and preprocess data before feeding the data to machine learning algorithms
</p>

In [1]:
import pandas as pd
from io import StringIO

In [4]:
csv_data = '''
A,B,C,D
1.0, 2.0, 3.0, 4.0
5.0,6.0,8.0
10.0,11.0,12.0,
'''
df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   8.0  NaN
2  10.0  11.0  12.0  NaN

In [5]:
df.isnull().sum()

A    0
B    0
C    0
D    2
dtype: int64

In [7]:
## drop rows with missing values 
df.dropna(axis = 0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [8]:
## drop rows with missing values based on a certain column

df.dropna(subset=['D'], axis =0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

<p>We can also drop columns that have atleast one NaN in any row</p>

In [9]:
df.dropna(axis =1)

      A     B     C
0   1.0   2.0   3.0
1   5.0   6.0   8.0
2  10.0  11.0  12.0

<p>
The danger of dropping NaN or missing data is that we can end up removing a lot of samples, which could leave us with
less than meaninful data to proceed with our modelling or to even learn fom the data.
</p>

<h3>Imputing Missing Values</h3>