## Supervised Learning Premier

<p>
The quality of data and the amount of useful information it contains is very key to the results of the machine learning algorithms.
Its important to examine and preprocess data before feeding the data to machine learning algorithms
</p>

In [29]:
import pandas as pd
from io import StringIO

In [30]:
csv_data = '''
A,B,C,D
1.0, 2.0, 3.0, 4.0
5.0,6.0,8.0
10.0,11.0,12.0,
'''
df = pd.read_csv(StringIO(csv_data))
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   8.0  NaN
2  10.0  11.0  12.0  NaN

In [31]:
df.isnull().sum()

A    0
B    0
C    0
D    2
dtype: int64

In [32]:
## drop rows with missing values 
df.dropna(axis = 0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

In [33]:
## drop rows with missing values based on a certain column

df.dropna(subset=['D'], axis =0)

     A    B    C    D
0  1.0  2.0  3.0  4.0

<p>We can also drop columns that have atleast one NaN in any row</p>

In [34]:
df.dropna(axis =1)

      A     B     C
0   1.0   2.0   3.0
1   5.0   6.0   8.0
2  10.0  11.0  12.0

<p>
The danger of dropping NaN or missing data is that we can end up removing a lot of samples, which could leave us with
less than meaninful data to proceed with our modelling or to even learn fom the data.
</p>

<h3>Imputing Missing Values</h3>

<p>To avoid losing too much valuable data, we can adop another approach that interpolates numerical data hence 
replacing the missing values</p>

In [35]:
from sklearn.impute import SimpleImputer

In [36]:
imputer = SimpleImputer(strategy = 'mean',)
imputer.fit(df)

SimpleImputer()

In [37]:
imputer.statistics_

array([5.33333333, 6.33333333, 7.66666667, 4.        ])

In [38]:
#df.mean().values

In [39]:
df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   8.0  NaN
2  10.0  11.0  12.0  NaN

In [40]:
X = imputer.transform(df)

In [41]:
new_df = pd.DataFrame(X, columns = df.columns)
new_df

      A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0   8.0  4.0
2  10.0  11.0  12.0  4.0

<p>We replaced each null value with the mean, which has been computed for each column</p>

### Dealing with categorical data

<p>
Categorical data can be classified into ordinal and nominal data.
</p>

<p>Ordinal features: Are categorical values that can be ordered/ arranged/ sorted. For example a t-shirt size can be XL > L > M > S </p>

<p>Nominal features: Do not imply any order, for example it could be color, or Language type, we cannot say one is larger os smaller than the other</p>

In [42]:
df = pd.DataFrame([['Green', 'M', 10.1, 'class1'],
                 ['Red','L', 13.5, 'class2'],
                 ['Blue','XL',15.3, 'class1']])
df.columns = ['color', 'size', 'price','class_label']
df

   color size  price class_label
0  Green    M   10.1      class1
1    Red    L   13.5      class2
2   Blue   XL   15.3      class1

### Let's try to map ordinal categorical variables using an assumption, for example: 

XL = L + 1 = M + 2

In [43]:
size_mapping = {
    'XL': 3,
    'L' : 2,
    'M' : 1
}
df['size'] = df['size'].map(size_mapping)

In [44]:
df

   color  size  price class_label
0  Green     1   10.1      class1
1    Red     2   13.5      class2
2   Blue     3   15.3      class1

#### If we want to reverse the mapping, this is what we can do

In [45]:
inverse_mapping = {v: k for k, v in size_mapping.items()}
df['size_r'] = df['size'].map(inverse_mapping)

In [46]:
df

   color  size  price class_label size_r
0  Green     1   10.1      class1      M
1    Red     2   13.5      class2      L
2   Blue     3   15.3      class1     XL

## Notes:

<p>
The zip() function is used to combine multiple iterables such as lists,
dictionaries and tuples into iterator of tuple. Each tuple will contain 
corresponding elements from the input iterables.
</p>

In [72]:
names = ["Fred","Alice","Andrew"]
scores = [78, 89, 78]

score_each = dict(zip(names, scores))

In [75]:
score_each

{'Fred': 78, 'Alice': 89, 'Andrew': 78}

In [76]:
paired = list(zip(names, scores))
print(paired)

[('Fred', 78), ('Alice', 89), ('Andrew', 78)]

In [77]:
### Unpacking a zipped object

names, scores = zip(*paired)
print(names)
print(scores)

('Fred', 'Alice', 'Andrew')
(78, 89, 78)

In [79]:
for name, score in zip(names, scores):
    print(f'{name} scored {score}')

Fred scored 78
Alice scored 89
Andrew scored 78

###### Handling unequal length variable iterables using: zip_longest

In [80]:
from itertools import zip_longest
list1 = [10, 45, 78]
list2 = ['A','B']

result = list(zip_longest(list1, list2, fillvalue ='N/A'))
print(result)

[(10, 'A'), (45, 'B'), (78, 'N/A')]

In [82]:
list(zip(list1, list2))

## as we can see above that zip will stop at the shortest one, and will not combine the iterables whose length has not been matched

[(10, 'A'), (45, 'B')]